### ISSUE TITLE
使用eBPF对指定的可执行程序进行访问控制

### ISSUE THREAD

**Issue by dejavudwh** [bytedance/vArmor#25]
文档中表示BPF enforcer不支持对指定的可执行程序进行访问控制，对此有一点疑惑想请教。

如果在hook点上获取当前的task_struct，通过`task->mm->exe_file->f_path.dentry->d_iname`获取到当前可执行文件到路径，并通过eBPF Map和用户提供的策略文件进行匹配，来确认是否进行访问控制。

不知道这个方法是否可行。

<img width="940" alt="image" src="https://github.com/bytedance/vArmor/assets/47321059/f1c21515-6dbc-44f7-b4b4-2d8ae3fa5ab6">

**Comment by Danny-Wei** [comment]
你好，感谢反馈。

由于无法像 AppArmor 那样使用进程安全上下文来标识和追踪目标进程及其子进程，因此这样实现会存在绕过的风险。

也可以考虑通过跟踪目标进程及子进程 pid 的方式来实现，但复杂度较高，后续可以进一步调研一下。

**Comment by dejavudwh** [comment]
@Danny-Wei 好的，非常感谢。
