### ISSUE TITLE
用eBPF代替Seccomp完成系统调用禁用操作

### ISSUE THREAD

**Issue by dejavudwh** [bytedance/vArmor#28]
您好，现在vArmor使用libseccomp-go来完成对系统调用的禁用操作，但是Seccomp在用户策略配置上的灵活性似乎没有那么强？

所以是否可以通过对`raw_tracepoint/sys_enter`进行hook，然后通过系统调用号对系统调用进行拦截。以及通过对`task_struct`的二进制可执行文件路径信息、Namespaces、Capabilities等信息的判断对当前进程的系统调用进行禁用，来向用户提供更多策略配置的空间。

更进一步地话，可以传递一些关键信息到用户空间，再在用户空间进行分析和记录。

不知这种方法是否可行？

新年快乐~感谢贡献！

**Comment by Danny-Wei** [comment]
你好，感谢反馈。我记得 raw tracepoint 只能用于 tracing，不可以用于修改参数或返回值。所以在系统调用入口处只能用于信息采集，无法实现系统调用的过滤。另外 seccomp-bpf 也是在 syscall_trace_enter 里处理的，使用 seccomp 进行系统调用过滤的主要缺点就是无法支持策略的动态变更。

祝新年快乐~

**Comment by Danny-Wei** [comment]
你好，感谢你反馈。

bpf_send_signal() 可以向当前进程发送信号，并由当前进程的任意线程进行异步处理。有些安全系统（例如 tetragon）会利用它来进行攻击防御，但我们认为这种方式过于激进，不太适合用于实现容器沙箱。这里有一篇文章详细描述了它的优缺点：[signaling-from-within-how-ebpf-interacts-with-signals](https://www.elastic.co/security-labs/signaling-from-within-how-ebpf-interacts-with-signals)

而使用 bpf_override_return() 也有一些限制，例如它只能在 kprobes 中使用，只支持 x86 架构。虽然可以使用它来实现类似功能，但如果用于容器沙箱场景，恐怕会带来更多的性能开销和兼容性问题。

目前 vArmor 集成 seccomp 的原则是尽可能地复用原生能力（即 Kubernetes、Runtime、Linux 对 Seccomp 的支持），从而避免多架构适配、性能开销增加、安全控制被绕过等问题。但由此而来的问题就是 Seccomp 相关策略无法动态变更。

**Comment by dejavudwh** [comment]
非常感谢前辈的回答！
