### ISSUE TITLE
eBPF functionality test failed

### ISSUE THREAD

**Issue by spoock1024** [bytedance/vArmor#9]
Hello, I'm testing the BPF functionality, and the test case is "demo2".

The logs for the agent are as follows:

```
I1123 07:54:23.066013       1 main.go:102] SETUP "msg"="Flags" "agent"=true "bpfExclusiveMode"=false "clientRateLimitBurst"=0 "clientRateLimitQPS"=0 "enableBpfEnforcer"=true "enableDefenseInDepth"=false "kubeconfig"="" "managerIP"="0.0.0.0" "restartExistWorkloads"=false "statusUpdateCycle"=7200000000000 "unloadAllAaProfile"=false "webhookMatchLabel"="sandbox.varmor.org/enable=true" "webhookTimeout"=10
I1123 07:54:23.095751       1 config.go:142] CreateClientConfig "msg"="Using in-cluster configuration" 
I1123 07:54:23.103363       1 main.go:141] SETUP "msg"="vArmor agent startup" 
I1123 07:54:23.177661       1 agent.go:172] AGENT "msg"="NewAgent" "nodeName"="sec-hidslog-03"
I1123 07:54:23.177692       1 agent.go:176] AGENT "msg"="initialize the AppArmor LSM" 
I1123 07:54:23.177704       1 agent.go:179] AGENT "msg"="setup the AppArmor feature ABI, abstractions, tunables and default profiles to /etc/apparmor.d" 
I1123 07:54:23.678065       1 agent.go:187] AGENT "msg"="setup the mock cri-containerd.apparmor.d profile for containerd" 
I1123 07:54:24.251489       1 agent.go:209] AGENT "msg"="initialize the BPF LSM" 
I1123 07:54:24.251538       1 enforcer.go:85] AGENT/BPF-ENFORCER "msg"="remove memory lock" 
I1123 07:54:24.251545       1 enforcer.go:92] AGENT/BPF-ENFORCER "msg"="parses the ebpf program into a CollectionSpec" 
I1123 07:54:24.353075       1 enforcer.go:147] AGENT/BPF-ENFORCER "msg"="load ebpf program and maps into the kernel" 
I1123 07:55:09.151990       1 enforcer.go:154] AGENT/BPF-ENFORCER "msg"="attach VarmorCapable to the LSM hook point" 
I1123 07:55:09.207475       1 enforcer.go:163] AGENT/BPF-ENFORCER "msg"="attach VarmorFileOpen to the LSM hook point" 
I1123 07:55:09.209028       1 enforcer.go:172] AGENT/BPF-ENFORCER "msg"="attach VarmorPathSymlink to the LSM hook point" 
I1123 07:55:09.210645       1 enforcer.go:181] AGENT/BPF-ENFORCER "msg"="attach VarmorPathLink to the LSM hook point" 
I1123 07:55:09.212335       1 enforcer.go:190] AGENT/BPF-ENFORCER "msg"="attach VarmorPathRename to the LSM hook point" 
I1123 07:55:09.213928       1 enforcer.go:199] AGENT/BPF-ENFORCER "msg"="attach VarmorBprmCheckSecurity to the LSM hook point" 
I1123 07:55:09.215592       1 enforcer.go:208] AGENT/BPF-ENFORCER "msg"="attach VarmorSocketConnect to the LSM hook point" 
I1123 07:55:09.217235       1 enforcer.go:217] AGENT/BPF-ENFORCER "msg"="attach VarmorPtraceAccessCheck to the LSM hook point" 
I1123 07:55:09.218806       1 enforcer.go:226] AGENT/BPF-ENFORCER "msg"="attach VarmorMount to the LSM hook point" 
I1123 07:55:09.220408       1 enforcer.go:235] AGENT/BPF-ENFORCER "msg"="attach VarmorMoveMount to the LSM hook point" 
I1123 07:55:09.221817       1 enforcer.go:244] AGENT/BPF-ENFORCER "msg"="attach VarmorUmount to the LSM hook point" 
I1123 07:55:09.255722       1 main.go:165] SETUP "msg"="vArmor agent is online" 
I1123 07:55:09.255816       1 agent.go:578] AGENT "msg"="starting" 
I1123 07:55:09.356618       1 monitor.go:151] AGENT/RUNTIME-MONITOR/eventHandler() "msg"="start watching the containerd events" 
I1123 07:55:09.356682       1 enforcer.go:275] AGENT/BPF-ENFORCER/eventHandler() "msg"="start handle the containerd events" 
I1123 07:55:11.369743       1 agent.go:346] AGENT/handleCreateOrUpdateArmorProfile() "msg"="ArmorProfile created or updated" "labels"=null "name"="varmor-demo-demo-2" "namespace"="demo" "profile mode"="enforce" "profile name"="varmor-demo-demo-2"
I1123 07:55:11.369771       1 agent.go:447] AGENT/handleCreateOrUpdateArmorProfile() "msg"="saving and applying the BPF profile ('varmor-demo-demo-2')" 
I1123 07:55:11.369782       1 agent.go:455] AGENT/handleCreateOrUpdateArmorProfile() "msg"="send succeeded status to manager" 
E1123 07:57:48.607300       1 monitor.go:184] AGENT/RUNTIME-MONITOR/eventHandler() "msg"="monitor.retrieveContainerInfo() failed" "error"="container \"0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704\" in namespace \"k8s.io\": not found" "container id"="0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704" "pid"=24125
E1123 08:09:51.110518       1 monitor.go:184] AGENT/RUNTIME-MONITOR/eventHandler() "msg"="monitor.retrieveContainerInfo() failed" "error"="container \"0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704\" in namespace \"k8s.io\": not found" "container id"="0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704" "pid"=46160
I1123 08:10:01.863807       1 agent.go:462] AGENT/handleDeleteArmorProfile() "msg"="ArmorProfile deleted" "name"="varmor-demo-demo-2" "namespace"="demo"
I1123 08:10:01.863847       1 agent.go:474] AGENT/handleDeleteArmorProfile() "msg"="unloading the BPF profile ('varmor-demo-demo-2')" 
I1123 08:11:04.290026       1 agent.go:346] AGENT/handleCreateOrUpdateArmorProfile() "msg"="ArmorProfile created or updated" "labels"=null "name"="varmor-demo-demo-2" "namespace"="demo" "profile mode"="enforce" "profile name"="varmor-demo-demo-2"
I1123 08:11:04.290052       1 agent.go:447] AGENT/handleCreateOrUpdateArmorProfile() "msg"="saving and applying the BPF profile ('varmor-demo-demo-2')" 
I1123 08:11:04.290062       1 agent.go:455] AGENT/handleCreateOrUpdateArmorProfile() "msg"="send succeeded status to manager" 
I1123 08:13:21.020106       1 agent.go:346] AGENT/handleCreateOrUpdateArmorProfile() "msg"="ArmorProfile created or updated" "labels"=null "name"="varmor-demo-demo-2" "namespace"="demo" "profile mode"="enforce" "profile name"="varmor-demo-demo-2"
I1123 08:13:21.020131       1 agent.go:447] AGENT/handleCreateOrUpdateArmorProfile() "msg"="saving and applying the BPF profile ('varmor-demo-demo-2')" 
I1123 08:13:21.020143       1 agent.go:455] AGENT/handleCreateOrUpdateArmorProfile() "msg"="send succeeded status to manager" 
E1123 08:21:55.166952       1 monitor.go:184] AGENT/RUNTIME-MONITOR/eventHandler() "msg"="monitor.retrieveContainerInfo() failed" "error"="container \"0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704\" in namespace \"k8s.io\": not found" "container id"="0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704" "pid"=69657
```

At the same time, I have enabled debug logging for eBPF, but during the runtime, I haven't seen any output:

```
cat  /sys/kernel/debug/tracing/trace_pipe
```

I'm not sure if I have misconfigured something, leading to eBPF not taking effect. Is there any way to resolve this issue?

-----

It seems like I may have found the reason. The issue lies within the `SaveAndApplyBpfProfile` function:

```go
func (enforcer *BpfEnforcer) SaveAndApplyBpfProfile(profileName string, bpfContent varmor.BpfContent) error {
	enforcer.log.Info("saveAndApplyBpfProfile", "profile", profileName, "new", bpfContent)
	enforcer.pretreatment(&bpfContent)

	// save/update the BPF profile to the cache
	if profile, ok := enforcer.bpfProfileCache[profileName]; ok {
		if reflect.DeepEqual(bpfContent, profile.bpfContent) {
			// nothing need to update
			enforcer.log.Info("the BPF profile is not changed, nothing need to update", "profile", profileName, "old", profile.bpfContent)
			return nil
		}
		enforcer.log.Info("update the BPF profile", "profile", profileName, "new", bpfContent)
		profile.bpfContent = bpfContent
		enforcer.bpfProfileCache[profileName] = profile
	} else {
		enforcer.log.Info("save the BPF profile", "profile", profileName, "new", bpfContent)
		profile := bpfProfile{
			bpfContent:     bpfContent,
			containerCache: make(map[string]enforceID),
		}
		enforcer.bpfProfileCache[profileName] = profile
	}

	// apply the BPF profile to the kernel for the existing containers
	profile := enforcer.bpfProfileCache[profileName]
	enforcer.log.Info("before foreach")
	for _, enforceID := range profile.containerCache {
		enforcer.log.Info("apply the BPF profile", "profile", profileName, "new", profile.bpfContent)
		err := enforcer.applyProfile(enforceID.mntNsID, profile.bpfContent)
		if err != nil {
			return err
		}
	}
	enforcer.log.Info("after foreach")
	return nil
}
```

The issue appears to be that in the `SaveAndApplyBpfProfile` function, the `containerCache` within the `profile` struct is not initialized, causing the subsequent `for` loop to not execute and consequently preventing the execution of `applyProfile` to apply the eBPF rules.

Subsequent log analysis reveals:

```
I1123 11:28:44.059566       1 enforcer.go:460] AGENT/BPF-ENFORCER "msg"="before foreach" 
I1123 11:28:44.059574       1 enforcer.go:468] AGENT/BPF-ENFORCER "msg"="after foreach" 
```

It can be observed that the code within the `for` loop did not execute.

Could you please confirm if my analysis is correct?

**Comment by Danny-Wei** [comment]
Sorry for the late response. 

Is your testing environment using k8s + Docker? In a k8s + Docker environment, Docker utilizes the "moby" namespace of the containerd rather than the "k8s.io" namespace. Currently, vArmor is only compatible with the k8s + containerd environment. So, retrieving container information may result in an error, such as `container \"0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704\" in namespace \"k8s.io\": not found`

**Comment by spoock1024** [comment]
> Sorry for the late response.
> 
> Is your testing environment using k8s + Docker? In a k8s + Docker environment, Docker utilizes the "moby" namespace of the containerd rather than the "k8s.io" namespace. Currently, vArmor is only compatible with the k8s + containerd environment. So, retrieving container information may result in an error, such as `container \"0ba9c31f2c46095118576db6a2664ace4dd2433799415abcc4b968b4806a4704\" in namespace \"k8s.io\": not found`

```
systemctl status k3s
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-11-24 16:52:56 CST; 3min 48s ago
       Docs: https://k3s.io
    Process: 2583949 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 2583951 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 2583952 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 2583953 (k3s-server)
      Tasks: 206
     Memory: 2.1G
        CPU: 29.120s
     CGroup: /system.slice/k3s.service
             ├─   3276 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 439f335540f0b114bbbc0f57f76c5224d3abda>
             ├─  13046 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 41a424de6829a7a7404446435d421b1fda307d>
             ├─  13347 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id ef06c607ddb5eda0f2f25df725d81672d33815>
             ├─  13835 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 01dfa7a9fe66f603c22a1a902836ee8ddf42ea>
             ├─  14356 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 76bb0ac64169296b357cbbedd6d3b468f55a60>
             ├─2455106 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 347884b9ba4f8b5813ce83680547792d3dff8d>
             ├─2455111 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id fb8a4280fe94c83c68f882b0eae36a847bbddc>
             ├─2455142 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 19495eaf5faad41630495958c13245bcde6a2b>
             ├─2455161 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id 0042c396b9ddacccb01283e0dfae074c6a9c98>
             ├─2458452 /var/lib/rancher/k3s/data/b20b68fab02222c85f08adc9d865ac2052f2f2f831a883e3b42654cf04acf31c/bin/containerd-shim-runc-v2 -namespace k8s.io -id c9ea9ff94046e5f754b50d48a78db20f11a290>
             ├─2583953 /usr/local/bin/k3s server
             └─2584002 containerd

```
My environment is `k3s+containerd`
The output confirms that my local `k3s` environment indeed uses `containerd` as the container runtime, and the namespace is `k8s.io`.

**Comment by Danny-Wei** [comment]
Understood, I will set up an environment with k3s+containerd to investigate this issue.

**Comment by Danny-Wei** [comment]
In my k3s environment, containerd by default utilizes `/run/k3s/containerd/containerd.sock` as the endpoint address. You can verify the containerd endpoint address using the `crictl info` command. So, it is necessary to update the hostPath for the containerd endpoint with the following command.

```
helm install varmor varmor-0.5.4.tgz \
    --namespace varmor --create-namespace \
    --set image.registry="elkeid-cn-beijing.cr.volces.com" \
    --set bpfLsmEnforcer.enabled=true \
    --set bpfLsmEnforcer.enabled=true \
    --set "agent.bpfLsmEnforcer.volumes[0].hostPath.type=Directory,agent.bpfLsmEnforcer.volumes[0].hostPath.path=/run/k3s/containerd/,agent.bpfLsmEnforcer.volumes[0].name=containerd" \
    --set "agent.bpfLsmEnforcer.volumes[1].hostPath.type=Directory,agent.bpfLsmEnforcer.volumes[1].hostPath.path=/proc,agent.bpfLsmEnforcer.volumes[1].name=procfs"
```

At this point, the agent can run normally and the sandbox is enabled for the specified containers.

**Comment by spoock1024** [comment]
I installed vArmor according to the instructions you provided, but when I tested it with demo2 I found that it still didn't take effect. Below is the log from my agent. How should I further troubleshoot the issue?
```
I1127 07:04:02.253880       1 config.go:136] CreateClientConfig "msg"="Using in-cluster configuration" 
I1127 07:04:02.254657       1 main.go:129] SETUP "msg"="vArmor agent startup" 
I1127 07:04:02.267298       1 agent.go:145] AGENT "msg"="NewAgent" "nodeName"="nodename"
I1127 07:04:02.267341       1 agent.go:149] AGENT "msg"="initialize the AppArmor LSM" 
I1127 07:04:02.267361       1 agent.go:152] AGENT "msg"="setup the AppArmor feature ABI, abstractions, tunables and default profiles to /etc/apparmor.d" 
I1127 07:04:02.352211       1 agent.go:160] AGENT "msg"="setup the mock cri-containerd.apparmor.d profile for containerd" 
I1127 07:04:02.851792       1 agent.go:182] AGENT "msg"="initialize the BPF LSM" 
I1127 07:04:02.851869       1 enforcer.go:85] AGENT/BPF-ENFORCER "msg"="remove memory lock" 
I1127 07:04:02.851882       1 enforcer.go:92] AGENT/BPF-ENFORCER "msg"="parses the ebpf program into a CollectionSpec" 
I1127 07:04:02.863267       1 enforcer.go:147] AGENT/BPF-ENFORCER "msg"="load ebpf program and maps into the kernel" 
I1127 07:04:50.367236       1 enforcer.go:154] AGENT/BPF-ENFORCER "msg"="attach VarmorCapable to the LSM hook point" 
I1127 07:04:50.511587       1 enforcer.go:163] AGENT/BPF-ENFORCER "msg"="attach VarmorFileOpen to the LSM hook point" 
I1127 07:04:50.513304       1 enforcer.go:172] AGENT/BPF-ENFORCER "msg"="attach VarmorPathSymlink to the LSM hook point" 
I1127 07:04:50.515074       1 enforcer.go:181] AGENT/BPF-ENFORCER "msg"="attach VarmorPathLink to the LSM hook point" 
I1127 07:04:50.517346       1 enforcer.go:190] AGENT/BPF-ENFORCER "msg"="attach VarmorPathRename to the LSM hook point" 
I1127 07:04:50.518903       1 enforcer.go:199] AGENT/BPF-ENFORCER "msg"="attach VarmorBprmCheckSecurity to the LSM hook point" 
I1127 07:04:50.520435       1 enforcer.go:208] AGENT/BPF-ENFORCER "msg"="attach VarmorSocketConnect to the LSM hook point" 
I1127 07:04:50.522043       1 enforcer.go:217] AGENT/BPF-ENFORCER "msg"="attach VarmorPtraceAccessCheck to the LSM hook point" 
I1127 07:04:50.523638       1 enforcer.go:226] AGENT/BPF-ENFORCER "msg"="attach VarmorMount to the LSM hook point" 
I1127 07:04:50.525550       1 enforcer.go:235] AGENT/BPF-ENFORCER "msg"="attach VarmorMoveMount to the LSM hook point" 
I1127 07:04:50.527267       1 enforcer.go:244] AGENT/BPF-ENFORCER "msg"="attach VarmorUmount to the LSM hook point" 
I1127 07:04:50.554714       1 main.go:153] SETUP "msg"="vArmor agent is online" 
I1127 07:04:50.554756       1 agent.go:543] AGENT "msg"="starting" 
I1127 07:04:50.655504       1 monitor.go:151] AGENT/RUNTIME-MONITOR/eventHandler() "msg"="start watching the containerd events" 
I1127 07:04:50.655524       1 enforcer.go:275] AGENT/BPF-ENFORCER/eventHandler() "msg"="start handle the containerd events" 
I1127 07:05:48.736707       1 agent.go:311] AGENT/handleCreateOrUpdateArmorProfile() "msg"="ArmorProfile created or updated" "labels"=null "name"="varmor-demo-demo-2" "namespace"="demo" "profile mode"="enforce" "profile name"="varmor-demo-demo-2"
I1127 07:05:48.736733       1 agent.go:412] AGENT/handleCreateOrUpdateArmorProfile() "msg"="saving and applying the BPF profile ('varmor-demo-demo-2')" 
I1127 07:05:48.736750       1 agent.go:420] AGENT/handleCreateOrUpdateArmorProfile() "msg"="send succeeded status to manager" 
I1127 07:05:57.949554       1 agent.go:311] AGENT/handleCreateOrUpdateArmorProfile() "msg"="ArmorProfile created or updated" "labels"=null "name"="varmor-demo-demo-2" "namespace"="demo" "profile mode"="enforce" "profile name"="varmor-demo-demo-2"
I1127 07:05:57.949580       1 agent.go:412] AGENT/handleCreateOrUpdateArmorProfile() "msg"="saving and applying the BPF profile ('varmor-demo-demo-2')" 
I1127 07:05:57.949594       1 agent.go:420] AGENT/handleCreateOrUpdateArmorProfile() "msg"="send succeeded status to manager" 
```

**Comment by spoock1024** [comment]
> This is the output of my bpftool.
> 
> ```
> $ bpftool prog show | grep lsm
> 7453: lsm  name varmor_bprm_che  tag 62b5da55b87c47d1  gpl
> 7454: lsm  name varmor_capable  tag ed898eba4c8a67e6  gpl
> 7455: lsm  name varmor_file_ope  tag 31c044ebfa181f1b  gpl
> 7456: lsm  name varmor_mount  tag 14c00e67297e8cf4  gpl
> 7457: lsm  name varmor_move_mou  tag faf08c29a1b8edab  gpl
> 7458: lsm  name varmor_path_lin  tag df3be27ecd236413  gpl
> 7459: lsm  name varmor_path_lin  tag 36d255922ab7210e  gpl
> 7460: lsm  name varmor_path_ren  tag 1d5a092444a3103f  gpl
> 7461: lsm  name varmor_path_ren  tag 36d255922ab7210e  gpl
> 7462: lsm  name varmor_path_sym  tag f021103ef9824cc0  gpl
> 7463: lsm  name varmor_ptrace_a  tag 7a47df68544c33f4  gpl
> 7464: lsm  name varmor_socket_c  tag e8a49111f3d96557  gpl
> 7465: lsm  name varmor_umount  tag 6aa52370ce8eab29  gpl
> ```
> 
> The following is the information of the node I have created using k3s.
> 
> ```
> kubectl get pods --all-namespaces
> NAMESPACE      NAME                                     READY   STATUS             RESTARTS        AGE
> kube-system    local-path-provisioner-957fdf8bc-25s62   1/1     Running            0               4d4h
> kube-system    svclb-traefik-d371557d-qvm7t             2/2     Running            0               4d4h
> kube-system    coredns-77ccd57875-4578c                 1/1     Running            1 (4d4h ago)    4d5h
> kube-system    traefik-64f55bb67d-zm9d7                 1/1     Running            0               4d4h
> kube-system    metrics-server-648b5df564-vmqnm          1/1     Running            0               4d4h
> varmor         varmor-agent-w7zrd                       1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-mfk5c          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-kk2dv          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-xj4mp          1/1     Running            0               99m
> demo           demo-2-bd854d6ff-74f8z                   2/2     Running            0               98m
> ```
> 
> When I run `kubectl exec -n demo demo-2-bd854d6ff-74f8z -c c0 -- cat /run/secrets/kubernetes.io/serviceaccount/token`, I can still get the result normally.
> 
> At the same time, I have confirmed that the agent no longer has the error `'CONTAINER_ID" in namespace "k8s.io": not found'.`

I retested it, and the eBPF functionality is working as expected.

I have a new issue now. I have already enabled the debug functionality for eBPF, and the code has been changed to the following

```c
#define DEBUG_PRINT(fmt, args...) \
  bpf_printk(fmt, ##args)
```

However, when I use the command `cat /sys/kernel/debug/tracing/trace_pipe` on the host machine of the node, I cannot see any output. Do I need additional configuration for this? Or are there other ways to view the logs?

**Comment by Danny-Wei** [comment]
> This is the output of my bpftool.
> 
> ```
> $ bpftool prog show | grep lsm
> 7453: lsm  name varmor_bprm_che  tag 62b5da55b87c47d1  gpl
> 7454: lsm  name varmor_capable  tag ed898eba4c8a67e6  gpl
> 7455: lsm  name varmor_file_ope  tag 31c044ebfa181f1b  gpl
> 7456: lsm  name varmor_mount  tag 14c00e67297e8cf4  gpl
> 7457: lsm  name varmor_move_mou  tag faf08c29a1b8edab  gpl
> 7458: lsm  name varmor_path_lin  tag df3be27ecd236413  gpl
> 7459: lsm  name varmor_path_lin  tag 36d255922ab7210e  gpl
> 7460: lsm  name varmor_path_ren  tag 1d5a092444a3103f  gpl
> 7461: lsm  name varmor_path_ren  tag 36d255922ab7210e  gpl
> 7462: lsm  name varmor_path_sym  tag f021103ef9824cc0  gpl
> 7463: lsm  name varmor_ptrace_a  tag 7a47df68544c33f4  gpl
> 7464: lsm  name varmor_socket_c  tag e8a49111f3d96557  gpl
> 7465: lsm  name varmor_umount  tag 6aa52370ce8eab29  gpl
> ```
> 
> The following is the information of the node I have created using k3s.
> 
> ```
> kubectl get pods --all-namespaces
> NAMESPACE      NAME                                     READY   STATUS             RESTARTS        AGE
> kube-system    local-path-provisioner-957fdf8bc-25s62   1/1     Running            0               4d4h
> kube-system    svclb-traefik-d371557d-qvm7t             2/2     Running            0               4d4h
> kube-system    coredns-77ccd57875-4578c                 1/1     Running            1 (4d4h ago)    4d5h
> kube-system    traefik-64f55bb67d-zm9d7                 1/1     Running            0               4d4h
> kube-system    metrics-server-648b5df564-vmqnm          1/1     Running            0               4d4h
> varmor         varmor-agent-w7zrd                       1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-mfk5c          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-kk2dv          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-xj4mp          1/1     Running            0               99m
> demo           demo-2-bd854d6ff-74f8z                   2/2     Running            0               98m
> ```
> 
> When I run `kubectl exec -n demo demo-2-bd854d6ff-74f8z -c c0 -- cat /run/secrets/kubernetes.io/serviceaccount/token`, I can still get the result normally.
> 
> At the same time, I have confirmed that the agent no longer has the error `'CONTAINER_ID" in namespace "k8s.io": not found'.`



> This is the output of my bpftool.
> 
> ```
> $ bpftool prog show | grep lsm
> 7453: lsm  name varmor_bprm_che  tag 62b5da55b87c47d1  gpl
> 7454: lsm  name varmor_capable  tag ed898eba4c8a67e6  gpl
> 7455: lsm  name varmor_file_ope  tag 31c044ebfa181f1b  gpl
> 7456: lsm  name varmor_mount  tag 14c00e67297e8cf4  gpl
> 7457: lsm  name varmor_move_mou  tag faf08c29a1b8edab  gpl
> 7458: lsm  name varmor_path_lin  tag df3be27ecd236413  gpl
> 7459: lsm  name varmor_path_lin  tag 36d255922ab7210e  gpl
> 7460: lsm  name varmor_path_ren  tag 1d5a092444a3103f  gpl
> 7461: lsm  name varmor_path_ren  tag 36d255922ab7210e  gpl
> 7462: lsm  name varmor_path_sym  tag f021103ef9824cc0  gpl
> 7463: lsm  name varmor_ptrace_a  tag 7a47df68544c33f4  gpl
> 7464: lsm  name varmor_socket_c  tag e8a49111f3d96557  gpl
> 7465: lsm  name varmor_umount  tag 6aa52370ce8eab29  gpl
> ```
> 
> The following is the information of the node I have created using k3s.
> 
> ```
> kubectl get pods --all-namespaces
> NAMESPACE      NAME                                     READY   STATUS             RESTARTS        AGE
> kube-system    local-path-provisioner-957fdf8bc-25s62   1/1     Running            0               4d4h
> kube-system    svclb-traefik-d371557d-qvm7t             2/2     Running            0               4d4h
> kube-system    coredns-77ccd57875-4578c                 1/1     Running            1 (4d4h ago)    4d5h
> kube-system    traefik-64f55bb67d-zm9d7                 1/1     Running            0               4d4h
> kube-system    metrics-server-648b5df564-vmqnm          1/1     Running            0               4d4h
> varmor         varmor-agent-w7zrd                       1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-mfk5c          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-kk2dv          1/1     Running            0               99m
> varmor         varmor-manager-5fdb74cc76-xj4mp          1/1     Running            0               99m
> demo           demo-2-bd854d6ff-74f8z                   2/2     Running            0               98m
> ```
> 
> When I run `kubectl exec -n demo demo-2-bd854d6ff-74f8z -c c0 -- cat /run/secrets/kubernetes.io/serviceaccount/token`, I can still get the result normally.
> 
> At the same time, I have confirmed that the agent no longer has the error `'CONTAINER_ID" in namespace "k8s.io": not found'.`

In demo-2, we have set the annotation `container.bpf.security.beta.varmor.org/c0: unconfined`, meaning vArmor will not apply a profile on the 'c0' container. Please try it again with c0 container.

**Comment by spoock1024** [comment]
Thank you very much. Following your advice, I have already solved the problem.
