### ISSUE TITLE
about Prerequisites for linux

### ISSUE THREAD

**Issue by dzy176** [bytedance/vArmor#92]
BPF LSM was introduced after linux 5.7, but in README of vArmor shows that kernel version need >= 5.10, cloud you please tell me why?

**Comment by Danny-Wei** [comment]
Thanks for asking. To implement certain policy primitives, we have utilized a mix of bpf2bpf function calls and tailcalls. This feature requires kernel 5.10 or higher on the x86_64 architecture.

**Comment by dzy176** [comment]
@Danny-Wei Thanks for your reply. It is really a nice project to learn BPF LSM.
